/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rresult

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun basicTest() {
        val demo: RResult<String, Int> = RResult.success("demo")
        assertEquals(demo.value, "demo")
    }
}
